### ISSUE TITLE
Test SMTP i produktions-war

### ISSUE THREAD

**Issue by toband88** [skltp/tak#4]
Hej!

Kan man lägga issues här? Alternativt, kan någon anvisa till rätt ställe?

Märkte precis att när vi kör tak-web 2.5.0 så startar den upp greenmail-servern (com.icegreen.greenmail.smtp.SmtpServer.run), trots att den endast borde köras i test-paketeringen. Vi kör med tak-web-warfilen från Ineras Nexus (https://nexus.drift.inera.se/repository/maven-public/se/skltp/tak/tak-web/<senaste-version>/tak-web-<senaste-version>.war) och har dubbelkollat så att grails.env=prod. Borde inte greenmail vara inaktiverat i en prod-paketering?

Lite miljöinfo:
Tomcat9.0.62
OpenJdk8u322
Tak-web2.5.0
Windows Server

Vänligen,
Andreas Torbiörnsson
Region Dalarna

**Comment by bjorpe** [comment]
Hej,
Denna bugg ska inte längre vara aktuell efter version 3.0 av TAK som innehåller en större refaktorering av tak-web.

Vi hanterar normalt inte buggar denna väg utan hänvisar till Ineras normala rutiner, se https://www.inera.se/kontakta-oss/felanmalan-och-anvandarstod/

Mvh Björn Pettersson, Applikationsförvaltning NTjP
